apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arc-
spec:
  entrypoint: arc
  templates:
  - name: arc
    dag:
      tasks:
        - name: arc
          templateRef:
            name: arc
            template: arcClient
          arguments:
            parameters:  
            - name: configUri
              value: https://raw.githubusercontent.com/tripl-ai/arc-starter/master/examples/kubernetes/nyctaxi.ipynb
            - name: parameters
              value: "--ETL_CONF_DATA_URL=s3a://nyc-tlc/trip*data --ETL_CONF_JOB_URL=https://raw.githubusercontent.com/tripl-ai/arc-starter/master/examples/kubernetes"
